# Week 1: Census Data Analysis

## Notes

### About the PDB

- Data is from the Census Planning Database (PDB) (full dataset is downloadable as a .csv).
- The PDB contains data from both the 2010 decennial census and the 2010-2014 American Community Survey (ACS). Since the purpose of the ACS is to measure changing social and economic characteristics of the population, we primarily refer to ACS variables in this analysis.
- PDB data is at the census tract or block group (which is more granular) level.
- Variable names are explained here: https://api.census.gov/data/2016/pdb/blockgroup/variables.html, https://api.census.gov/data/2016/pdb/tract/variables.html

### Getting geographic information
- Locations are given as State/County/Tract/BG codes. In order to interpret these as longitude/latitude coordinates, we need a mapping from block group/census tract to geography.
- Census tract to longitude/latitude coordinates are available in the Census Tracts Gazetteer file (https://www.census.gov/geo/maps-data/data/gazetteer2017.html). This is what we use in this preliminary analysis.
- Mappings from block group can be accessed by opening the relevant shapefiles in ArcGIS (http://gif.berkeley.edu/resources/arcgis_education_edition.html).
    - About Shapefiles: https://www2.census.gov/geo/pdfs/maps-data/data/tiger/tgrshp2017/TGRSHP2017_TechDoc_Ch2.pdf

In [2]:
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
%pylab inline

Populating the interactive namespace from numpy and matplotlib

In [3]:
import numpy as np

In [4]:
# Census Planning Database - Block Group
# full_pdb16_bg_df = pd.read_csv("raw-data/pdb2016_bg_v8_us.csv", encoding="ISO-8859-1")

# Census Planning Database - Census Tract
full_pdb16_tr_df = pd.read_csv("raw-data/pdb2016_tr_v8_us.csv", encoding="ISO-8859-1")

### Alameda County

In [14]:
def df_for_county(county_name):
    return full_pdb16_tr_df.loc[full_pdb16_tr_df['County_name'] == county_name]

alameda_tr_df = df_for_county("Alameda County")

In [20]:
# Importing longitude/latitude mappings
gaz_tracts_df = pd.read_csv("raw-data/2017_gaz_tracts_06.csv", encoding="ISO-8859-1")

def map_lat_long_geoid(geoid_min, geoid_max, df):
    # Adds latitude and longitude columns to the dataframe.
    # Modifies df in place.
    lat_long_df = gaz_tracts_df[gaz_tracts_df['GEOID'] >= geoid_min]
    lat_long_df = lat_long_df[lat_long_df['GEOID'] < geoid_max]
    lat_long_df = lat_long_df[['GEOID', 'INTPTLAT', 'INTPTLONG                                                                                                                             ']]

    num_tracts = len(lat_long_df) - 1
    gidtr_lat, gidtr_long = {}, {}
    for i in range(num_tracts):
        geoid, lat, long = lat_long_df.iloc[i][0], lat_long_df.iloc[i][1], lat_long_df.iloc[i][2]
        gidtr_lat[geoid], gidtr_long[geoid] = lat, long
    
    df['Latitude'] = df['GIDTR'].map(gidtr_lat)
    df['Longitude'] = df['GIDTR'].map(gidtr_long)

In [17]:
map_lat_long_geoid(6001000000, 6002000000, alameda_tr_df)
alameda_tr_df

/Users/Helen/anaconda3/lib/python3.4/site-packages/IPython/kernel/__main__.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/Users/Helen/anaconda3/lib/python3.4/site-packages/IPython/kernel/__main__.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

,GIDTR,State,State_name,County,County_name,Tract,Flag,Num_BGs_in_Tract,LAND_AREA,AIAN_LAND,...,pct_Census_Mail_Returns_CEN_2010,pct_Vacants_CEN_2010,pct_Deletes_CEN_2010,pct_Census_UAA_CEN_2010,pct_Mailback_Count_CEN_2010,pct_FRST_FRMS_CEN_2010,pct_RPLCMNT_FRMS_CEN_2010,pct_BILQ_Mailout_count_CEN_2010,Latitude,Longitude
3563,6001400100,6,California,1,Alameda County,400100,NaN,1,2.657,0,...,77.76,5.05,0,3.25,91.70,77.69,0.07,NaN,37.867628,-122.231946
3564,6001400200,6,California,1,Alameda County,400200,NaN,2,0.230,0,...,79.14,6.42,0,3.42,90.16,79.14,0.00,NaN,37.848139,-122.249597
3565,6001400300,6,California,1,Alameda County,400300,NaN,4,0.427,0,...,77.20,4.12,0,5.76,90.13,69.50,7.70,NaN,37.840598,-122.254436
3566,6001400400,6,California,1,Alameda County,400400,NaN,3,0.271,0,...,77.05,4.86,0,5.06,90.08,69.10,7.96,NaN,37.848280,-122.257453
3567,6001400500,6,California,1,Alameda County,400500,NaN,3,0.227,0,...,71.76,4.01,0,6.13,89.86,65.04,6.72,NaN,37.848541,-122.264728
3568,6001400600,6,California,1,Alameda County,400600,NaN,2,0.115,0,...,67.79,6.75,0,4.68,88.57,60.00,7.79,NaN,37.841991,-122.264888
3569,6001400700,6,California,1,Alameda County,400700,NaN,4,0.340,0,...,60.92,5.42,0,7.62,86.96,49.82,11.10,NaN,37.841767,-122.272353
3570,6001400800,6,California,1,Alameda County,400800,NaN,3,0.268,0,...,62.31,5.30,0,7.70,87.00,52.11,10.21,NaN,37.845467,-122.283394
3571,6001400900,6,California,1,Alameda County,400900,NaN,2,0.165,0,...,60.50,6.51,0,7.81,85.68,49.74,10.76,NaN,37.839491,-122.280265
3572,6001401000,6,California,1,Alameda County,401000,NaN,6,0.446,0,...,55.11,5.61,0,11.43,82.96,44.96,10.15,NaN,37.831226,-122.271901
3573,6001401100,6,California,1,Alameda County,401100,NaN,4,0.343,0,...,67.94,4.59,0,7.29,88.12,60.46,7.48,NaN,37.830504,-122.263858
3574,6001401200,6,California,1,Alameda County,401200,NaN,3,0.258,0,...,74.74,4.45,0,5.28,90.27,66.82,7.92,NaN,37.830614,-122.257900
3575,6001401300,6,California,1,Alameda County,401300,NaN,3,0.331,0,...,54.15,5.85,0,17.10,77.05,45.41,8.75,NaN,37.818116,-122.266698
3576,6001401400,6,California,1,Alameda County,401400,NaN,3,0.292,0,...,42.53,7.20,0,19.63,73.17,35.66,6.87,NaN,37.820756,-122.273387
3577,6001401500,6,California,1,Alameda County,401500,NaN,3,0.181,0,...,44.07,8.01,0,22.94,69.05,35.51,8.56,NaN,37.822929,-122.280634
3578,6001401600,6,California,1,Alameda County,401600,NaN,2,0.245,0,...,42.28,6.30,0,21.95,71.75,34.15,8.13,NaN,37.817372,-122.281482
3579,6001401700,6,California,1,Alameda County,401700,NaN,3,2.240,0,...,46.64,5.58,0,26.61,67.81,38.07,8.56,NaN,37.822518,-122.307774
3580,6001401800,6,California,1,Alameda County,401800,NaN,2,0.115,0,...,42.99,8.08,0,21.02,70.90,33.61,9.38,NaN,37.809533,-122.298236
3581,6001402200,6,California,1,Alameda County,402200,NaN,3,0.274,0,...,52.17,6.83,0,13.86,79.31,43.12,9.05,NaN,37.806352,-122.296307
3582,6001402400,6,California,1,Alameda County,402400,NaN,2,0.130,0,...,55.04,6.22,0,11.76,82.02,45.38,9.66,NaN,37.812031,-122.282457
3583,6001402500,6,California,1,Alameda County,402500,NaN,2,0.141,0,...,52.41,2.28,0,10.46,87.27,42.23,10.19,NaN,37.805731,-122.284780
3584,6001402600,6,California,1,Alameda County,402600,NaN,1,0.123,0,...,67.63,4.58,0,8.64,86.78,60.34,7.29,NaN,37.804270,-122.279955
3585,6001402700,6,California,1,Alameda County,402700,NaN,2,0.154,0,...,48.12,12.37,0,9.14,78.49,41.94,6.18,95.3,37.810387,-122.276991
3586,6001402800,6,California,1,Alameda County,402800,NaN,2,0.154,0,...,54.20,7.44,0,15.84,76.72,47.65,6.55,NaN,37.808718,-122.271500
3587,6001402900,6,California,1,Alameda County,402900,NaN,1,0.150,0,...,69.69,2.50,0,8.17,89.33,62.20,7.49,NaN,37.807172,-122.266785
3588,6001403000,6,California,1,Alameda County,403000,NaN,2,0.137,0,...,76.38,7.40,0,7.87,84.72,72.82,3.55,NaN,37.800434,-122.270727
3589,6001403100,6,California,1,Alameda County,403100,NaN,1,0.134,0,...,60.26,3.53,0,23.66,72.81,55.56,4.71,NaN,37.802274,-122.275501
3590,6001403300,6,California,1,Alameda County,403300,NaN,2,0.358,0,...,69.89,6.27,0,5.96,87.77,62.84,7.05,NaN,37.794431,-122.266324
3591,6001403400,6,California,1,Alameda County,403400,NaN,4,0.254,0,...,57.57,6.73,0,17.90,75.38,49.30,8.27,NaN,37.802648,-122.262660
3592,6001403501,6,California,1,Alameda County,403501,NaN,3,0.258,0,...,68.23,2.71,0,8.53,88.75,60.84,7.39,NaN,37.817740,-122.260050
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3894,6001450742,6,California,1,Alameda County,450742,NaN,3,3.003,0,...,80.20,1.29,0,4.29,94.42,80.20,0.00,NaN,37.667212,-121.827468
3895,6001450743,6,California,1,Alameda County,450743,NaN,2,1.658,0,...,64.95,1.56,0,3.80,94.64,64.95,0.00,NaN,37.693121,-121.892390
3896,6001450744,6,California,1,Alameda County,450744,NaN,2,1.007,0,...,84.43,1.01,0,1.27,97.72,84.43,0.00,NaN,37.696996,-121.865151
3897,6001450745,6,California,1,Alameda County,450745,NaN,2,2.815,0,...,81.96,1.43,0,1.82,96.75,81.96,0.00,NaN,37.680333,-121.851931
3898,6001450746,6,California,1,Alameda County,450746,NaN,2,0.669,0,...,80.35,1.11,0,3.96,94.93,80.35,0.00,NaN,37.673693,-121.868581
3899,6001450750,6,California,1,Alameda County,450750,NaN,1,0.654,0,...,60.14,3.11,0,13.00,83.89,60.14,0.00,NaN,37.705484,-121.861069
3900,6001450751,6,California,1,Alameda County,450751,NaN,1,3.780,0,...,70.00,3.65,0,8.92,87.43,70.00,0.00,NaN,37.716400,-121.842839
3901,6001450752,6,California,1,Alameda County,450752,NaN,1,6.789,0,...,70.83,2.65,0,2.14,95.21,70.83,0.00,NaN,37.740920,-121.823992
3902,6001451101,6,California,1,Alameda County,451101,NaN,5,213.467,0,...,71.73,5.53,0,7.33,87.14,63.25,8.47,NaN,37.639684,-121.663357
3903,6001451102,6,California,1,Alameda County,451102,NaN,2,1.846,0,...,82.45,1.28,0,1.36,97.36,82.45,0.00,NaN,37.650686,-121.786159
3904,6001451201,6,California,1,Alameda County,451201,NaN,3,1.419,0,...,73.34,1.39,0,3.51,95.10,73.34,0.00,NaN,37.712907,-121.741815
3905,6001451202,6,California,1,Alameda County,451202,NaN,3,17.748,0,...,73.57,1.85,0,4.47,93.68,73.57,0.00,NaN,37.734691,-121.769004
3906,6001451300,6,California,1,Alameda County,451300,NaN,3,4.899,0,...,76.80,0.81,0,2.81,96.38,76.80,0.00,NaN,37.690637,-121.818639
3907,6001451401,6,California,1,Alameda County,451401,NaN,3,1.790,0,...,72.60,1.44,0,2.75,95.80,72.60,0.00,NaN,37.695984,-121.762931
3908,6001451403,6,California,1,Alameda County,451403,NaN,2,0.260,0,...,75.74,1.93,0,1.67,96.41,75.74,0.00,NaN,37.691232,-121.784246
3909,6001451404,6,California,1,Alameda County,451404,NaN,3,0.647,0,...,62.85,2.79,0,4.12,93.08,62.85,0.00,NaN,37.685275,-121.780352
3910,6001451501,6,California,1,Alameda County,451501,NaN,2,1.951,0,...,77.22,1.39,0,2.59,96.03,77.22,0.00,NaN,37.673348,-121.736968
3911,6001451503,6,California,1,Alameda County,451503,NaN,4,1.033,0,...,73.98,2.26,0,4.16,93.58,73.98,0.00,NaN,37.684952,-121.748997
3912,6001451504,6,California,1,Alameda County,451504,NaN,1,1.250,0,...,75.33,1.32,0,2.98,95.70,75.33,0.00,NaN,37.697940,-121.732237
3913,6001451505,6,California,1,Alameda County,451505,NaN,2,0.530,0,...,83.61,0.69,0,1.04,98.27,83.61,0.00,NaN,37.689445,-121.724672
3914,6001451506,6,California,1,Alameda County,451506,NaN,2,0.328,0,...,69.55,2.23,0,3.21,94.55,69.55,0.00,NaN,37.683352,-121.729186
3915,6001451601,6,California,1,Alameda County,451601,NaN,2,1.520,0,...,75.44,1.87,0,5.83,92.30,75.44,0.00,NaN,37.668380,-121.760745
3916,6001451602,6,California,1,Alameda County,451602,NaN,4,1.163,0,...,71.97,2.28,0,6.83,90.89,71.97,0.00,NaN,37.671249,-121.775621
3917,6001451701,6,California,1,Alameda County,451701,NaN,3,0.472,0,...,77.82,1.97,0,2.16,95.86,77.82,0.00,NaN,37.672108,-121.787947
3918,6001451703,6,California,1,Alameda County,451703,NaN,2,0.658,0,...,79.94,0.61,0,2.50,96.90,79.94,0.00,NaN,37.667295,-121.800999
3919,6001451704,6,California,1,Alameda County,451704,NaN,3,0.773,0,...,77.84,1.57,0,1.93,96.51,77.84,0.00,NaN,37.662123,-121.790063
3920,6001981900,6,California,1,Alameda County,981900,NaN,1,1.446,0,...,46.15,7.69,0,7.69,84.62,34.62,11.54,NaN,37.803357,-122.319896
3921,6001982000,6,California,1,Alameda County,982000,NaN,1,0.490,0,...,66.67,11.90,0,11.90,76.19,59.52,7.14,NaN,37.796160,-122.293536
3922,6001983200,6,California,1,Alameda County,983200,NaN,1,0.191,0,...,42.32,23.03,0,21.78,55.19,42.32,0.00,NaN,37.795946,-122.277268
3923,6001990000,6,California,1,Alameda County,990000,1,1,0.000,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [18]:
# Some preliminary datasets
gender_alameda_tr_df = alameda_tr_df[['Latitude', 'Longitude', 'LAND_AREA', 'Tot_Population_ACS_10_14', 'pct_Females_ACS_10_14']]
ethnicity_alameda_tr_df = alameda_tr_df[['Latitude', 'Longitude', 'LAND_AREA', 'Tot_Population_ACS_10_14', 'NH_AIAN_alone_ACS_10_14', 'NH_Asian_alone_ACS_10_14', 'NH_Blk_alone_ACS_10_14', 'NH_NHOPI_alone_ACS_10_14', 'NH_SOR_alone_ACS_10_14', 'NH_White_alone_ACS_10_14']]

health_ins_alameda_tr_df = alameda_tr_df[['Latitude', 'Longitude', 'LAND_AREA', 'Tot_Population_ACS_10_14', 'No_Health_Ins_ACS_10_14', 'pct_No_Health_Ins_ACS_10_14', 'One_Health_Ins_ACS_10_14', 'pct_One_Health_Ins_ACS_10_14', 'pct_TwoPHealthIns_ACS_10_14', 'Two_Plus_Health_Ins_ACS_10_14']]
income_alameda_tr_df = alameda_tr_df[['Latitude', 'Longitude', 'LAND_AREA', 'Tot_Population_ACS_10_14', 'Med_HHD_Inc_ACS_10_14', 'Prs_Blw_Pov_Lev_ACS_10_14', 'PUB_ASST_INC_ACS_10_14']]

In [19]:
income_alameda_tr_df

,Latitude,Longitude,LAND_AREA,Tot_Population_ACS_10_14,Med_HHD_Inc_ACS_10_14,Prs_Blw_Pov_Lev_ACS_10_14,PUB_ASST_INC_ACS_10_14
3563,37.867628,-122.231946,2.657,3385,"$165,625",137,0
3564,37.848139,-122.249597,0.230,1939,"$134,531",78,0
3565,37.840598,-122.254436,0.427,5428,"$71,618",460,180
3566,37.848280,-122.257453,0.271,4279,"$98,824",307,40
3567,37.848541,-122.264728,0.227,3516,"$73,837",530,47
3568,37.841991,-122.264888,0.115,1750,"$57,639",143,36
3569,37.841767,-122.272353,0.340,4396,"$41,023",832,9
3570,37.845467,-122.283394,0.268,3218,"$59,018",243,36
3571,37.839491,-122.280265,0.165,2031,"$60,089",243,50
3572,37.831226,-122.271901,0.446,5505,"$38,403",1630,112
3573,37.830504,-122.263858,0.343,4240,"$56,401",645,68
3574,37.830614,-122.257900,0.258,2345,"$76,897",183,74
3575,37.818116,-122.266698,0.331,3815,"$36,782",1209,117
3576,37.820756,-122.273387,0.292,4297,"$30,023",1771,153
3577,37.822929,-122.280634,0.181,2131,"$44,728",488,29
3578,37.817372,-122.281482,0.245,1919,"$31,280",771,92
3579,37.822518,-122.307774,2.240,2603,"$61,563",593,99
3580,37.809533,-122.298236,0.115,1794,"$31,125",571,101
3581,37.806352,-122.296307,0.274,2446,"$36,224",648,57
3582,37.812031,-122.282457,0.130,2846,"$28,606",835,125
3583,37.805731,-122.284780,0.141,1909,"$18,967",949,188
3584,37.804270,-122.279955,0.123,1029,"$20,259",359,29
3585,37.810387,-122.276991,0.154,1647,"$33,125",409,84
3586,37.808718,-122.271500,0.154,3299,"$20,534",1378,85
3587,37.807172,-122.266785,0.150,1399,"$23,825",350,23
3588,37.800434,-122.270727,0.137,2471,"$16,469",747,23
3589,37.802274,-122.275501,0.134,1782,"$53,750",387,6
3590,37.794431,-122.266324,0.358,3785,"$60,893",818,68
3591,37.802648,-122.262660,0.254,4361,"$38,109",689,37
3592,37.817740,-122.260050,0.258,4495,"$37,454",1140,39
...,...,...,...,...,...,...,...
3894,37.667212,-121.827468,3.003,4745,"$118,646",45,7
3895,37.693121,-121.892390,1.658,5887,"$92,188",403,36
3896,37.696996,-121.865151,1.007,4876,"$120,284",208,30
3897,37.680333,-121.851931,2.815,5829,"$152,014",21,35
3898,37.673693,-121.868581,0.669,3284,"$115,000",218,0
3899,37.705484,-121.861069,0.654,3961,"$84,091",403,51
3900,37.716400,-121.842839,3.780,4045,"$179,523",28,17
3901,37.740920,-121.823992,6.789,5575,"$162,891",86,0
3902,37.639684,-121.663357,213.467,7024,"$136,280",297,2
3903,37.650686,-121.786159,1.846,4031,"$141,713",106,0
3904,37.712907,-121.741815,1.419,6768,"$91,446",395,41
3905,37.734691,-121.769004,17.748,3936,"$110,391",157,0
3906,37.690637,-121.818639,4.899,7116,"$105,238",284,59
3907,37.695984,-121.762931,1.790,6312,"$91,250",666,34
3908,37.691232,-121.784246,0.260,2100,"$96,359",143,4
3909,37.685275,-121.780352,0.647,6217,"$55,639",654,114
3910,37.673348,-121.736968,1.951,4524,"$78,786",174,18
3911,37.684952,-121.748997,1.033,5564,"$77,778",364,37
3912,37.697940,-121.732237,1.250,1673,"$107,850",53,0
3913,37.689445,-121.724672,0.530,3314,"$140,417",58,0
3914,37.683352,-121.729186,0.328,3555,"$76,181",499,73
3915,37.668380,-121.760745,1.520,5045,"$131,196",114,41
3916,37.671249,-121.775621,1.163,6740,"$91,250",291,29
3917,37.672108,-121.787947,0.472,2895,"$95,848",101,0
3918,37.667295,-121.800999,0.658,4492,"$133,722",138,68
3919,37.662123,-121.790063,0.773,4228,"$92,944",173,37
3920,37.803357,-122.319896,1.446,28,"$48,333",0,0
3921,37.796160,-122.293536,0.490,83,"$145,278",0,0
3922,37.795946,-122.277268,0.191,591,"$121,071",42,2
3923,NaN,NaN,0.000,0,NaN,0,0

In [35]:
gender_alameda_tr_df.to_csv('datasets/alameda/gender_alameda_tr.csv')
ethnicity_alameda_tr_df.to_csv('datasets/alameda/ethnicity_alameda_tr.csv')
health_ins_alameda_tr_df.to_csv('datasets/alameda/health_ins_alameda_tr.csv')
income_alameda_tr_df.to_csv('datasets/alameda/income_alameda_tr.csv')

### Other Bay Area Counties

In [37]:
sanfrancisco_tr_df = df_for_county("San Francisco County")

In [30]:
map_lat_long_geoid(6075000000, 6076000000, sanfrancisco_tr_df)

/Users/Helen/anaconda3/lib/python3.4/site-packages/IPython/kernel/__main__.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/Users/Helen/anaconda3/lib/python3.4/site-packages/IPython/kernel/__main__.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [32]:
gender_sanfrancisco_tr_df = sanfrancisco_tr_df[['Latitude', 'Longitude', 'LAND_AREA', 'Tot_Population_ACS_10_14', 'pct_Females_ACS_10_14']]
ethnicity_sanfrancisco_tr_df = sanfrancisco_tr_df[['Latitude', 'Longitude', 'LAND_AREA', 'Tot_Population_ACS_10_14', 'NH_AIAN_alone_ACS_10_14', 'NH_Asian_alone_ACS_10_14', 'NH_Blk_alone_ACS_10_14', 'NH_NHOPI_alone_ACS_10_14', 'NH_SOR_alone_ACS_10_14', 'NH_White_alone_ACS_10_14']]

health_ins_sanfrancisco_tr_df = sanfrancisco_tr_df[['Latitude', 'Longitude', 'LAND_AREA', 'Tot_Population_ACS_10_14', 'No_Health_Ins_ACS_10_14', 'pct_No_Health_Ins_ACS_10_14', 'One_Health_Ins_ACS_10_14', 'pct_One_Health_Ins_ACS_10_14', 'pct_TwoPHealthIns_ACS_10_14', 'Two_Plus_Health_Ins_ACS_10_14']]
income_sanfrancisco_tr_df = sanfrancisco_tr_df[['Latitude', 'Longitude', 'LAND_AREA', 'Tot_Population_ACS_10_14', 'Med_HHD_Inc_ACS_10_14', 'Prs_Blw_Pov_Lev_ACS_10_14', 'PUB_ASST_INC_ACS_10_14']]

In [36]:
gender_sanfrancisco_tr_df.to_csv('datasets/san-francisco/gender_sanfrancisco_tr.csv')
ethnicity_sanfrancisco_tr_df.to_csv('datasets/san-francisco/ethnicity_sanfrancisco_tr.csv')
health_ins_sanfrancisco_tr_df.to_csv('datasets/san-francisco/health_ins_sanfrancisco_tr.csv')
income_sanfrancisco_tr_df.to_csv('datasets/san-francisco/income_sanfrancisco_tr.csv')

In [47]:
sanmateo_tr_df = df_for_county("San Mateo County")

In [48]:
map_lat_long_geoid(6081000000, 6082000000, sanmateo_tr_df)

/Users/Helen/anaconda3/lib/python3.4/site-packages/IPython/kernel/__main__.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/Users/Helen/anaconda3/lib/python3.4/site-packages/IPython/kernel/__main__.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [44]:
gender_sanmateo_tr_df = sanmateo_tr_df[['Latitude', 'Longitude', 'LAND_AREA', 'Tot_Population_ACS_10_14', 'pct_Females_ACS_10_14']]
ethnicity_sanmateo_tr_df = sanmateo_tr_df[['Latitude', 'Longitude', 'LAND_AREA', 'Tot_Population_ACS_10_14', 'NH_AIAN_alone_ACS_10_14', 'NH_Asian_alone_ACS_10_14', 'NH_Blk_alone_ACS_10_14', 'NH_NHOPI_alone_ACS_10_14', 'NH_SOR_alone_ACS_10_14', 'NH_White_alone_ACS_10_14']]

health_ins_sanmateo_tr_df = sanmateo_tr_df[['Latitude', 'Longitude', 'LAND_AREA', 'Tot_Population_ACS_10_14', 'No_Health_Ins_ACS_10_14', 'pct_No_Health_Ins_ACS_10_14', 'One_Health_Ins_ACS_10_14', 'pct_One_Health_Ins_ACS_10_14', 'pct_TwoPHealthIns_ACS_10_14', 'Two_Plus_Health_Ins_ACS_10_14']]
income_sanmateo_tr_df = sanmateo_tr_df[['Latitude', 'Longitude', 'LAND_AREA', 'Tot_Population_ACS_10_14', 'Med_HHD_Inc_ACS_10_14', 'Prs_Blw_Pov_Lev_ACS_10_14', 'PUB_ASST_INC_ACS_10_14']]

gender_sanmateo_tr_df.to_csv('datasets/san-mateo/gender_sanmateo_tr.csv')
ethnicity_sanmateo_tr_df.to_csv('datasets/san-mateo/ethnicity_sanmateo_tr.csv')
health_ins_sanmateo_tr_df.to_csv('datasets/san-mateo/health_ins_sanmateo_tr.csv')
income_sanmateo_tr_df.to_csv('datasets/san-mateo/income_sanmateo_tr.csv')

In [49]:
santaclara_tr_df = df_for_county("Santa Clara County")

In [51]:
map_lat_long_geoid(6085000000, 6086000000, santaclara_tr_df)

/Users/Helen/anaconda3/lib/python3.4/site-packages/IPython/kernel/__main__.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/Users/Helen/anaconda3/lib/python3.4/site-packages/IPython/kernel/__main__.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [52]:
gender_santaclara_tr_df = santaclara_tr_df[['Latitude', 'Longitude', 'LAND_AREA', 'Tot_Population_ACS_10_14', 'pct_Females_ACS_10_14']]
ethnicity_santaclara_tr_df = santaclara_tr_df[['Latitude', 'Longitude', 'LAND_AREA', 'Tot_Population_ACS_10_14', 'NH_AIAN_alone_ACS_10_14', 'NH_Asian_alone_ACS_10_14', 'NH_Blk_alone_ACS_10_14', 'NH_NHOPI_alone_ACS_10_14', 'NH_SOR_alone_ACS_10_14', 'NH_White_alone_ACS_10_14']]

health_ins_santaclara_tr_df = santaclara_tr_df[['Latitude', 'Longitude', 'LAND_AREA', 'Tot_Population_ACS_10_14', 'No_Health_Ins_ACS_10_14', 'pct_No_Health_Ins_ACS_10_14', 'One_Health_Ins_ACS_10_14', 'pct_One_Health_Ins_ACS_10_14', 'pct_TwoPHealthIns_ACS_10_14', 'Two_Plus_Health_Ins_ACS_10_14']]
income_santaclara_tr_df = santaclara_tr_df[['Latitude', 'Longitude', 'LAND_AREA', 'Tot_Population_ACS_10_14', 'Med_HHD_Inc_ACS_10_14', 'Prs_Blw_Pov_Lev_ACS_10_14', 'PUB_ASST_INC_ACS_10_14']]

gender_santaclara_tr_df.to_csv('datasets/santa-clara/gender_santaclara_tr.csv')
ethnicity_santaclara_tr_df.to_csv('datasets/santa-clara/ethnicity_santaclara_tr.csv')
health_ins_santaclara_tr_df.to_csv('datasets/santa-clara/health_ins_santaclara_tr.csv')
income_santaclara_tr_df.to_csv('datasets/santa-clara/income_santaclara_tr.csv')

In [72]:
def write_datasets_for_county(county_name, dir_path):
    # Gets the data for the county, maps the latitude/longitude coordinates,
    # and writes the relevant datasets.
    df = df_for_county(county_name)
    
    state, county = df['State'].iloc[0], df['County'].iloc[0]
    gidtr_min = int(str(state) + str(county).zfill(3) + '000000')
    gidtr_max = int(str(state) + str(county + 1).zfill(3) + '000000')
    map_lat_long_geoid(gidtr_min, gidtr_max, df)
    
    gender = df[['Latitude', 'Longitude', 'LAND_AREA', 'Tot_Population_ACS_10_14', 'pct_Females_ACS_10_14']]
    ethnicity = df[['Latitude', 'Longitude', 'LAND_AREA', 'Tot_Population_ACS_10_14', 'NH_AIAN_alone_ACS_10_14', 'NH_Asian_alone_ACS_10_14', 'NH_Blk_alone_ACS_10_14', 'NH_NHOPI_alone_ACS_10_14', 'NH_SOR_alone_ACS_10_14', 'NH_White_alone_ACS_10_14']]
    health_ins = df[['Latitude', 'Longitude', 'LAND_AREA', 'Tot_Population_ACS_10_14', 'No_Health_Ins_ACS_10_14', 'pct_No_Health_Ins_ACS_10_14', 'One_Health_Ins_ACS_10_14', 'pct_One_Health_Ins_ACS_10_14', 'pct_TwoPHealthIns_ACS_10_14', 'Two_Plus_Health_Ins_ACS_10_14']]
    income = df[['Latitude', 'Longitude', 'LAND_AREA', 'Tot_Population_ACS_10_14', 'Med_HHD_Inc_ACS_10_14', 'Prs_Blw_Pov_Lev_ACS_10_14', 'PUB_ASST_INC_ACS_10_14']]
    
    gender.to_csv(dir_path + "gender_" + county_name.lower().replace(" ", "") + "_tr.csv")
    ethnicity.to_csv(dir_path + "ethnicity_" + county_name.lower().replace(" ", "") + "_tr.csv")
    health_ins.to_csv(dir_path + "health_ins_" + county_name.lower().replace(" ", "") + "_tr.csv")
    income.to_csv(dir_path + "income_" + county_name.lower().replace(" ", "") + "_tr.csv")

In [74]:
write_datasets_for_county("Marin County", "datasets/marin/")
write_datasets_for_county("Contra Costa County", "datasets/contra-costa/")
write_datasets_for_county("Napa County", "datasets/napa/")
write_datasets_for_county("Sonoma County", "datasets/sonoma/")
write_datasets_for_county("Solano County", "datasets/solano/")

/Users/Helen/anaconda3/lib/python3.4/site-packages/IPython/kernel/__main__.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/Users/Helen/anaconda3/lib/python3.4/site-packages/IPython/kernel/__main__.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

# Pre-Process Census Data for Unknowns

## Contra Costa

### Ethnicity

In [4]:
pd.read_csv('census-datasets/contra-costa/ethnicity_contracostacounty_tr.csv')

,Unnamed: 0,Latitude,Longitude,LAND_AREA,Tot_Population_ACS_10_14,NH_AIAN_alone_ACS_10_14,NH_Asian_alone_ACS_10_14,NH_Blk_alone_ACS_10_14,NH_NHOPI_alone_ACS_10_14,NH_SOR_alone_ACS_10_14,NH_White_alone_ACS_10_14
0,4000,38.038123,-121.629968,30.506,4024.0,0.0,181.0,210.0,0.0,0.0,2566.0
1,4001,37.999316,-121.732928,1.378,6736.0,45.0,460.0,448.0,31.0,0.0,2889.0
2,4002,38.009414,-121.705822,2.363,3991.0,0.0,205.0,57.0,0.0,0.0,2056.0
3,4003,37.983711,-121.705654,1.670,6014.0,86.0,316.0,550.0,23.0,0.0,2294.0
4,4004,37.989109,-121.670210,7.252,8860.0,231.0,970.0,866.0,0.0,0.0,3108.0
5,4005,37.971409,-121.747864,2.031,6431.0,34.0,1158.0,1421.0,0.0,0.0,1463.0
6,4006,37.983675,-121.730632,2.652,10400.0,48.0,715.0,378.0,18.0,115.0,5758.0
7,4007,37.957794,-121.707487,2.513,8247.0,0.0,1136.0,527.0,1.0,0.0,3264.0
8,4008,37.936299,-121.671017,12.980,10735.0,63.0,369.0,502.0,6.0,0.0,4876.0
9,4009,37.943061,-121.758766,5.135,10676.0,23.0,1027.0,1637.0,36.0,0.0,4501.0
10,4010,37.942408,-121.714911,1.422,7307.0,0.0,620.0,46.0,56.0,0.0,5259.0
11,4011,37.947039,-121.732215,2.440,8878.0,0.0,906.0,801.0,0.0,0.0,5196.0
12,4012,37.928967,-121.708933,0.790,4950.0,0.0,61.0,168.0,0.0,25.0,2640.0
13,4013,37.910913,-121.701698,5.293,7907.0,0.0,587.0,41.0,0.0,0.0,5474.0
14,4014,37.883721,-121.749368,11.039,4020.0,0.0,718.0,107.0,0.0,0.0,2330.0
15,4015,37.858336,-121.622012,32.441,1363.0,0.0,9.0,9.0,0.0,0.0,750.0
16,4016,37.901159,-121.580709,3.438,3913.0,0.0,132.0,361.0,0.0,0.0,2995.0
17,4017,37.894860,-121.610638,0.997,4069.0,0.0,13.0,8.0,0.0,0.0,3458.0
18,4018,37.934724,-121.595891,17.349,7052.0,24.0,272.0,124.0,53.0,95.0,5150.0
19,4019,38.015857,-121.834562,3.154,6333.0,67.0,121.0,996.0,0.0,0.0,2185.0
20,4020,38.007797,-121.761924,2.896,2920.0,30.0,226.0,169.0,0.0,0.0,1525.0
21,4021,38.005333,-121.799441,0.692,5225.0,38.0,235.0,685.0,64.0,0.0,2196.0
22,4022,38.008574,-121.784536,0.643,3007.0,0.0,73.0,553.0,0.0,0.0,962.0
23,4023,37.986656,-121.815546,0.835,4362.0,10.0,121.0,392.0,0.0,0.0,1826.0
24,4024,38.000474,-121.815571,0.619,5139.0,13.0,43.0,234.0,0.0,0.0,1742.0
25,4025,38.002487,-121.848591,0.597,3379.0,19.0,166.0,469.0,16.0,44.0,926.0
26,4026,38.003702,-121.827801,0.272,4034.0,0.0,237.0,1208.0,150.0,0.0,549.0
27,4027,37.994685,-121.830871,0.580,4135.0,13.0,120.0,486.0,0.0,0.0,1478.0
28,4028,37.986034,-121.829459,1.191,6460.0,0.0,624.0,1290.0,9.0,0.0,2251.0
29,4029,37.991873,-121.796399,1.419,6690.0,0.0,452.0,760.0,36.0,0.0,3344.0
...,...,...,...,...,...,...,...,...,...,...,...
178,4178,37.958723,-122.323664,0.581,2505.0,15.0,186.0,535.0,0.0,5.0,745.0
179,4179,37.939878,-122.322335,0.395,2743.0,0.0,534.0,307.0,0.0,0.0,1233.0
180,4180,37.940308,-122.329952,0.499,5694.0,5.0,1099.0,692.0,22.0,45.0,1498.0
181,4181,37.948516,-122.339947,0.604,7401.0,0.0,896.0,988.0,0.0,0.0,892.0
182,4182,37.947619,-122.353813,0.319,3648.0,28.0,282.0,463.0,8.0,0.0,81.0
183,4183,37.939418,-122.341488,0.382,4642.0,0.0,535.0,617.0,0.0,23.0,786.0
184,4184,37.940257,-122.351821,0.254,4829.0,20.0,82.0,595.0,0.0,23.0,153.0
185,4185,37.941016,-122.362429,0.471,5968.0,0.0,491.0,1576.0,18.0,0.0,218.0
186,4186,37.933779,-122.363024,0.482,6821.0,11.0,231.0,1020.0,44.0,37.0,574.0
187,4187,37.944824,-122.404805,6.600,3091.0,0.0,247.0,211.0,0.0,0.0,2019.0
188,4188,37.928307,-122.356712,0.653,6260.0,0.0,97.0,2135.0,0.0,68.0,133.0
189,4189,37.897452,-122.356381,2.343,5898.0,0.0,956.0,1657.0,110.0,73.0,1684.0
190,4190,37.930198,-122.335073,0.752,7108.0,0.0,257.0,2529.0,0.0,128.0,542.0
191,4191,37.915991,-122.322995,0.740,6971.0,0.0,761.0,3008.0,147.0,0.0,512.0
192,4192,37.909020,-122.311712,0.515,5032.0,48.0,1310.0,626.0,13.0,0.0,2228.0
193,4193,37.934084,-122.312198,0.612,3825.0,0.0,720.0,242.0,0.0,22.0,2068.0
194,4194,37.924232,-122.295752,0.955,2668.0,0.0,539.0,204.0,0.0,0.0,1483.0
195,4195,37.927476,-122.308734,0.246,1265.0,26.0,461.0,47.0,0.0,0.0,630.0
196,4196,37.922674,-122.315595,0.399,3442.0,0.0,779.0,546.0,22.0,0.0,1157.0
197,4197,37.917044,-122.305922,0.310,2752.0,0.0,764.0,232.0,10.0,0.0,1539.0
198,4198,37.908968,-122.302215,0.256,2906.0,0.0,888.0,78.0,0.0,30.0,1383.0
199,4199,37.902240,-122.298067,0.262,2079.0,0.0,599.0,52.0,0.0,6.0,947.0
200,4200,37.901126,-122.305291,0.095,1628.0,0.0,612.0,179.0,8.0,0.0,535.0
201,4201,37.913939,-122.293478,0.390,2244.0,0.0,418.0,105.0,0.0,16.0,1311.0
202,4202,37.904556,-122.291176,0.238,1687.0,0.0,353.0,24.0,0.0,5.0,1221.0
203,4203,37.907192,-122.284314,0.534,2575.0,0.0,286.0,24.0,0.0,0.0,2082.0
204,4204,37.909418,-122.274879,0.391,2718.0,0.0,347.0,42.0,0.0,0.0,1983.0
205,4205,37.996338,-122.349183,4.508,11225.0,88.0,2713.0,1973.0,127.0,47.0,2139.0
206,4206,38.026408,-122.274457,0.816,2900.0,0.0,1715.0,297.0,0.0,0.0,306.0
207,4207,NaN,NaN,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [ ]:
set(pd.read_csv('census-datasets/alameda/poverty_level_alameda_tr_split.csv')['Variable'])

## Health Ins

In [7]:
pd.read_csv('census-datasets/alameda/income_alameda_tr.csv')

,Unnamed: 0,Latitude,Longitude,LAND_AREA,Tot_Population_ACS_10_14,Med_HHD_Inc_ACS_10_14,Prs_Blw_Pov_Lev_ACS_10_14,PUB_ASST_INC_ACS_10_14
0,3563,37.867628,-122.231946,2.657,3385.0,"$165,625",137.0,0.0
1,3564,37.848139,-122.249597,0.230,1939.0,"$134,531",78.0,0.0
2,3565,37.840598,-122.254436,0.427,5428.0,"$71,618",460.0,180.0
3,3566,37.848280,-122.257453,0.271,4279.0,"$98,824",307.0,40.0
4,3567,37.848541,-122.264728,0.227,3516.0,"$73,837",530.0,47.0
5,3568,37.841991,-122.264888,0.115,1750.0,"$57,639",143.0,36.0
6,3569,37.841767,-122.272353,0.340,4396.0,"$41,023",832.0,9.0
7,3570,37.845467,-122.283394,0.268,3218.0,"$59,018",243.0,36.0
8,3571,37.839491,-122.280265,0.165,2031.0,"$60,089",243.0,50.0
9,3572,37.831226,-122.271901,0.446,5505.0,"$38,403",1630.0,112.0
10,3573,37.830504,-122.263858,0.343,4240.0,"$56,401",645.0,68.0
11,3574,37.830614,-122.257900,0.258,2345.0,"$76,897",183.0,74.0
12,3575,37.818116,-122.266698,0.331,3815.0,"$36,782",1209.0,117.0
13,3576,37.820756,-122.273387,0.292,4297.0,"$30,023",1771.0,153.0
14,3577,37.822929,-122.280634,0.181,2131.0,"$44,728",488.0,29.0
15,3578,37.817372,-122.281482,0.245,1919.0,"$31,280",771.0,92.0
16,3579,37.822518,-122.307774,2.240,2603.0,"$61,563",593.0,99.0
17,3580,37.809533,-122.298236,0.115,1794.0,"$31,125",571.0,101.0
18,3581,37.806352,-122.296307,0.274,2446.0,"$36,224",648.0,57.0
19,3582,37.812031,-122.282457,0.130,2846.0,"$28,606",835.0,125.0
20,3583,37.805731,-122.284780,0.141,1909.0,"$18,967",949.0,188.0
21,3584,37.804270,-122.279955,0.123,1029.0,"$20,259",359.0,29.0
22,3585,37.810387,-122.276991,0.154,1647.0,"$33,125",409.0,84.0
23,3586,37.808718,-122.271500,0.154,3299.0,"$20,534",1378.0,85.0
24,3587,37.807172,-122.266785,0.150,1399.0,"$23,825",350.0,23.0
25,3588,37.800434,-122.270727,0.137,2471.0,"$16,469",747.0,23.0
26,3589,37.802274,-122.275501,0.134,1782.0,"$53,750",387.0,6.0
27,3590,37.794431,-122.266324,0.358,3785.0,"$60,893",818.0,68.0
28,3591,37.802648,-122.262660,0.254,4361.0,"$38,109",689.0,37.0
29,3592,37.817740,-122.260050,0.258,4495.0,"$37,454",1140.0,39.0
...,...,...,...,...,...,...,...,...
331,3894,37.667212,-121.827468,3.003,4745.0,"$118,646",45.0,7.0
332,3895,37.693121,-121.892390,1.658,5887.0,"$92,188",403.0,36.0
333,3896,37.696996,-121.865151,1.007,4876.0,"$120,284",208.0,30.0
334,3897,37.680333,-121.851931,2.815,5829.0,"$152,014",21.0,35.0
335,3898,37.673693,-121.868581,0.669,3284.0,"$115,000",218.0,0.0
336,3899,37.705484,-121.861069,0.654,3961.0,"$84,091",403.0,51.0
337,3900,37.716400,-121.842839,3.780,4045.0,"$179,523",28.0,17.0
338,3901,37.740920,-121.823992,6.789,5575.0,"$162,891",86.0,0.0
339,3902,37.639684,-121.663357,213.467,7024.0,"$136,280",297.0,2.0
340,3903,37.650686,-121.786159,1.846,4031.0,"$141,713",106.0,0.0
341,3904,37.712907,-121.741815,1.419,6768.0,"$91,446",395.0,41.0
342,3905,37.734691,-121.769004,17.748,3936.0,"$110,391",157.0,0.0
343,3906,37.690637,-121.818639,4.899,7116.0,"$105,238",284.0,59.0
344,3907,37.695983,-121.762931,1.790,6312.0,"$91,250",666.0,34.0
345,3908,37.691232,-121.784246,0.260,2100.0,"$96,359",143.0,4.0
346,3909,37.685275,-121.780352,0.647,6217.0,"$55,639",654.0,114.0
347,3910,37.673348,-121.736968,1.951,4524.0,"$78,786",174.0,18.0
348,3911,37.684952,-121.748997,1.033,5564.0,"$77,778",364.0,37.0
349,3912,37.697940,-121.732237,1.250,1673.0,"$107,850",53.0,0.0
350,3913,37.689445,-121.724671,0.530,3314.0,"$140,417",58.0,0.0
351,3914,37.683352,-121.729186,0.328,3555.0,"$76,181",499.0,73.0
352,3915,37.668380,-121.760745,1.520,5045.0,"$131,196",114.0,41.0
353,3916,37.671249,-121.775621,1.163,6740.0,"$91,250",291.0,29.0
354,3917,37.672108,-121.787947,0.472,2895.0,"$95,848",101.0,0.0
355,3918,37.667295,-121.800999,0.658,4492.0,"$133,722",138.0,68.0
356,3919,37.662123,-121.790063,0.773,4228.0,"$92,944",173.0,37.0
357,3920,37.803357,-122.319896,1.446,28.0,"$48,333",0.0,0.0
358,3921,37.796160,-122.293536,0.490,83.0,"$145,278",0.0,0.0
359,3922,37.795946,-122.277268,0.191,591.0,"$121,071",42.0,2.0
360,3923,NaN,NaN,0.000,0.0,NaN,0.0,0.0

In [6]:
set(pd.read_csv('census-datasets/alameda/poverty_level_alameda_tr_split.csv')['Variable'])

{'Above_poverty_level', 'Prs_Blw_Pov_Lev_ACS_10_14'}

In [9]:
health_ins_binarized = pd.read_csv('census-datasets/alameda/health_ins_alameda_tr_split_binarized.csv')

In [22]:
health_ins_binarized[(health_ins_binarized['variable'] == 'One_Plus_Health_Ins')\
                     & (np.abs(health_ins_binarized['Latitude'] - 37.867) < 5e-4)]

      Latitude   Longitude  value             variable
493  37.866788 -122.259979   6691  One_Plus_Health_Ins
495  37.866844 -122.277135   3867  One_Plus_Health_Ins
853  37.866788 -122.259979    975  One_Plus_Health_Ins
855  37.866844 -122.277135    848  One_Plus_Health_Ins

In [23]:
health_ins = pd.read_csv('census-datasets/alameda/health_ins_alameda_tr.csv')

In [24]:
health_ins.shape

(361, 11)

In [26]:
health_ins[np.abs(health_ins['Latitude'] - 37.867) < 5e-4]

,Unnamed: 0,Latitude,Longitude,LAND_AREA,Tot_Population_ACS_10_14,No_Health_Ins_ACS_10_14,pct_No_Health_Ins_ACS_10_14,One_Health_Ins_ACS_10_14,pct_One_Health_Ins_ACS_10_14,pct_TwoPHealthIns_ACS_10_14,Two_Plus_Health_Ins_ACS_10_14
133,3696,37.866788,-122.259979,0.158,8154,488,5.98,6691,82.06,11.96,975
135,3698,37.866844,-122.277135,0.282,5045,317,6.28,3867,76.65,16.81,848

In [30]:
health_ins_binarized.iloc[493]['Latitude'] - health_ins_binarized.iloc[855]['Latitude']

-5.660000000062837e-05

In [31]:
health_ins_binarized.shape

(1440, 4)

In [32]:
health_ins_binarized.iloc[3]

Latitude                     37.8483
Longitude                   -122.257
value                            292
variable     No_Health_Ins_ACS_10_14
Name: 3, dtype: object

In [38]:
health_ins_binarized.iloc[[3, 363, 723, 1083]]

      Latitude   Longitude  value                 variable
3     37.84828 -122.257453    292  No_Health_Ins_ACS_10_14
363   37.84828 -122.257453   3456      One_Plus_Health_Ins
723   37.84828 -122.257453    526      One_Plus_Health_Ins
1083  37.84828 -122.257453      5                  Unknown

### Add Two Health Ins to One Health Ins

In [43]:
health_ins_cleaned_df = pd.DataFrame.copy(health_ins_binarized.iloc[:720])

In [54]:
vals_to_add = np.zeros(shape=len(health_ins_cleaned_df,))

In [55]:
vals_to_add.shape

(720,)

In [56]:
# add one and two health ins populations together for each tract
for i in np.arange(720, 1080): 
    vals_to_add[i - 360] = health_ins_binarized.iloc[i]['value']

In [59]:
health_ins_cleaned_df['value'] = health_ins_cleaned_df['value'] + vals_to_add

### Split the Unknowns

In [68]:
unknown_pop_vals = np.array(health_ins_binarized.iloc[1080:]['value'])

In [79]:
vals_to_add = np.zeros(shape=len(health_ins_cleaned_df, ))

In [80]:
vals_to_add.shape

(720,)

In [81]:
for i in range(360): 
    no_ins_pop = health_ins_cleaned_df.iloc[i]['value']
    one_ins_pop = health_ins_cleaned_df.iloc[i + 360]['value']
    frac_no_ins = no_ins_pop / (no_ins_pop + one_ins_pop)
    frac_with_ins = 1.0 - frac_no_ins
    vals_to_add[i] = np.round(frac_no_ins * unknown_pop_vals[i], decimals=0)
    vals_to_add[360 + i] = np.round(frac_with_ins * unknown_pop_vals[i], decimals=0)

In [82]:
for i in range(360): 
    print(vals_to_add[i] + vals_to_add[360 + i] - unknown_pop_vals[i])

0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0

In [84]:
health_ins_cleaned_df['value'] = health_ins_cleaned_df['value'] + vals_to_add

In [85]:
health_ins_cleaned_df.shape

(720, 4)

In [86]:
health_ins.shape

(361, 11)

In [87]:
health_ins_cleaned_df.head()

    Latitude   Longitude  value                 variable
0  37.867628 -122.231946  114.0  No_Health_Ins_ACS_10_14
1  37.848139 -122.249597  105.0  No_Health_Ins_ACS_10_14
2  37.840598 -122.254436  404.0  No_Health_Ins_ACS_10_14
3  37.848280 -122.257453  292.0  No_Health_Ins_ACS_10_14
4  37.848541 -122.264728  555.0  No_Health_Ins_ACS_10_14

In [88]:
health_ins_cleaned_df.to_csv('census-datasets/alameda/health_ins_binarized_unknown_removed.csv')

## Race

In [95]:
race_split_df = pd.read_csv('census-datasets/alameda/ethnicity_alameda_tr_racial_split.csv')

In [102]:
race_split_df.head()

    Latitude   Longitude  Value                 Variable
0  37.671028 -121.913048      7  NH_AIAN_alone_ACS_10_14
1  37.551134 -121.805460      0  NH_AIAN_alone_ACS_10_14
2  37.866788 -122.259979     73  NH_AIAN_alone_ACS_10_14
3  37.698814 -122.123482      0  NH_AIAN_alone_ACS_10_14
4  37.556962 -122.021234      0  NH_AIAN_alone_ACS_10_14

In [104]:
set(race_split_df['Variable'].values)

{'NH_AIAN_alone_ACS_10_14',
 'NH_Asian_alone_ACS_10_14',
 'NH_Blk_alone_ACS_10_14',
 'NH_NHOPI_alone_ACS_10_14',
 'NH_SOR_alone_ACS_10_14',
 'NH_White_alone_ACS_10_14',
 'Other'}

In [128]:
vals_to_add = np.zeros(shape=len(race_split_df) - 360,)

In [129]:
unknown_pop_vals = np.array(race_split_df['Value'].iloc[2160:].values)

In [130]:
unknown_pop_vals.shape

(360,)

In [131]:
for i in range(360):
    indices = i + np.arange(0, 6) * 360
    pop_values = np.array(race_split_df.iloc[indices]['Value'].values)
    pop_fractions = pop_values / np.sum(pop_values)
    to_add = np.round(pop_fractions * unknown_pop_vals[i])
    for relative_index, true_index in enumerate(indices): 
        vals_to_add[true_index] = to_add[relative_index]

In [133]:
vals_to_add.shape

(2160,)

In [136]:
race_split_df_clean = pd.DataFrame.copy(race_split_df.iloc[:2160])

In [ ]:
race_s

In [138]:
race_split_df_clean['Value'] = race_split_df_clean['Value'] + vals_to_add

In [139]:
race_split_df_clean['Value'] - race_split_df.iloc[:2160]['Value']

0         1.0
1         0.0
2        17.0
3         0.0
4         0.0
5         0.0
6        49.0
7         5.0
8        24.0
9        17.0
10        6.0
11        3.0
12        0.0
13       29.0
14        0.0
15       17.0
16        4.0
17       10.0
18        0.0
19        0.0
20       15.0
21        7.0
22        9.0
23        2.0
24        0.0
25       19.0
26        0.0
27       23.0
28        0.0
29        6.0
        ...
2130    254.0
2131    196.0
2132    141.0
2133    359.0
2134    137.0
2135    388.0
2136    107.0
2137     79.0
2138    161.0
2139    252.0
2140     81.0
2141     31.0
2142    167.0
2143    202.0
2144    263.0
2145    138.0
2146    100.0
2147    204.0
2148    186.0
2149    145.0
2150    138.0
2151     65.0
2152     30.0
2153    161.0
2154     45.0
2155      4.0
2156     43.0
2157     67.0
2158     13.0
2159      0.0
Name: Value, Length: 2160, dtype: float64

In [142]:
race_split_df_clean.to_csv('census-datasets/alameda/ethnicity_alameda_tr_split_unknown_removed.csv')

In [141]:
vals_to_add

array([ 1.,  0., 17., ..., 67., 13.,  0.])

In [127]:
np.arange(0, 6) * 360 + 359

array([ 359,  719, 1079, 1439, 1799, 2159])

In [120]:
5 + np.arange(0, 7) * 360

array([   5,  365,  725, 1085, 1445, 1805, 2165])